apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: networking
data:
  config.yaml: |
    tunnel: 55fb8453-63a7-4c89-aca6-13e7eb040b31
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: crm-g3-k8s.ojaydiddy.site
        service: http://crm.default.svc.cluster.local:8080
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args: ["tunnel","--config","/etc/cloudflared/config.yaml","run"]
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "256Mi" }
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/credentials.json
          subPath: credentials.json
          readOnly: true
      volumes:
      - name: config
        configMap: { name: cloudflared-config }
      - name: creds
        secret: { secretName: cloudflared-credentials }
