services:
  crm:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    
  db:
    image: mysql:8.0.43
    restart: always
    #command: --skip-grant-tables --skip-networking=0
    environment:
      MYSQL_ROOT_PASSWORD: Secret5555
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crmpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8078:8080"

volumes:
  mysql_db_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.172.27.15,nfsvers=4,rw" # add ',nolock' if you see lock errors
      device: ":/mnt/application/class-crm-mysql"
