name: Ping
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}
jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Echo
        run: |
          echo "Hello from runner: ${{ runner.name }}"
          echo "Labels: ${{ runner.labels }}"
          echo "Repo: ${{ github.repository }}"
